version: "3.6"

services:
  gitlab:
    image: 'gitlab/gitlab-ce:latest'
    restart: always
    hostname: gitlab
    container_name: gitlab
    networks:
      gitlab:
        ipv4_address: 10.0.8.8
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url '$EXTERNAL_URL';
        nginx['enable'] = true;
        nginx['redirect_http_to_https'] = true;
        nginx['redirect_http_to_https_port'] = 80;
        nginx['ssl_certificate'] = '$SSL_CERTIFICATE';
        nginx['ssl_certificate_key'] = '$SSL_CERTIFICATE_KEY';
        nginx['client_max_body_size'] = '1024m';
        pages_external_url '$PAGES_EXTERNAL_URL';
        gitlab_pages['inplace_chroot'] = true;
        gitlab_pages['enable'] = true;
        pages_nginx['enable'] = true;
        pages_nginx['ssl_certificate'] = '$SSL_CERTIFICATE';
        pages_nginx['ssl_certificate_key'] = '$SSL_CERTIFICATE_KEY';
        gitlab_rails['time_zone'] = 'PRC';
        gitlab_rails['lfs_enabled'] = true;
        gitlab_rails['gitlab_email_enabled'] = true;
        gitlab_rails['gitlab_email_from'] = '$EMAIL_FROM';
        gitlab_rails['gitlab_email_display_name'] = '$EMAIL_DISPLAY_NAME';
        gitlab_rails['gitlab_email_reply_to'] = '$EMAIL_REPLY_TO';
        gitlab_rails['smtp_enable'] = $SMTP_ENABLE;
        gitlab_rails['smtp_address'] = '$SMTP_ADDRESS';
        gitlab_rails['smtp_port'] = $SMTP_PORT;
        gitlab_rails['smtp_user_name'] = '$SMTP_USER_NAME';
        gitlab_rails['smtp_password'] = '$SMTP_PASSWORD';
        gitlab_rails['smtp_domain'] = '$SMTP_DOMAIN';
        gitlab_rails['smtp_authentication'] = '$SMTP_AUTHENTICATION';
        gitlab_rails['smtp_enable_starttls_auto'] = $SMTP_ENABLE_STARTTLS_AUTO;
        gitlab_rails['smtp_tls'] = $SMTP_TLS;
    ports:
      - 22:22
      - 80:80
      - 443:443
    volumes:
      - $GITLAB_HOME/config:/etc/gitlab
      - $GITLAB_HOME/logs:/var/log/gitlab
      - $GITLAB_HOME/data:/var/opt/gitlab
networks:
  gitlab:
    name: gitlab
    ipam:
      driver: default
      config:
        - subnet: 10.0.8.0/24